# Generated by Django 4.2 on 2023-04-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddiction',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Addiction Name'),
        ),
    ]
