# Generated by Django 4.2 on 2023-04-09 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thrivetracker', '0002_alter_useraddiction_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_trackers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='timetracker',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_trackers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraddiction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_addictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstep',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MoneySaved',
        ),
    ]
