# Generated by Django 4.2 on 2023-04-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0003_moneytracker_alter_timetracker_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstep',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstep',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
