# Generated by Django 4.2 on 2023-04-09 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0004_userstep_completed_userstep_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracker',
            name='money_tracker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thrivetracker.moneytracker'),
        ),
    ]
