# Generated by Django 4.2 on 2023-04-09 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0005_timetracker_money_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneytracker',
            name='date',
        ),
        migrations.AddField(
            model_name='moneytracker',
            name='time_tracker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thrivetracker.timetracker'),
        ),
    ]
