# Generated by Django 4.2 on 2023-04-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0006_remove_moneytracker_date_moneytracker_time_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstep',
            name='swap_step',
        ),
    ]
