# Generated by Django 4.2 on 2023-04-09 22:22

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0007_remove_userstep_swap_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneytracker',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='useraddiction',
            name='name',
        ),
        migrations.AddField(
            model_name='timetracker',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='useraddiction',
            name='addiction',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moneytracker',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
