# Generated by Django 4.2 on 2023-04-09 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0009_remove_userstep_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracker',
            name='user_addiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thrivetracker.useraddiction'),
        ),
    ]
