# Generated by Django 4.2 on 2023-04-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0010_timetracker_user_addiction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='name',
            new_name='step',
        ),
    ]
