# Generated by Django 4.2 on 2023-04-10 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0012_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='money_tracker',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='time_tracker',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_addiction',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_step',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='money_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thrivetracker.moneytracker'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='time_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thrivetracker.timetracker'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_addiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thrivetracker.useraddiction'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thrivetracker.userstep'),
        ),
    ]
