# Generated by Django 4.2 on 2023-04-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0013_remove_userprofile_money_tracker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_step',
        ),
    ]
