# Generated by Django 4.2 on 2023-04-12 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thrivetracker', '0015_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('mood', models.CharField(max_length=150)),
                ('triggers', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='money_tracker',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='time_tracker',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_addiction',
        ),
        migrations.RemoveField(
            model_name='userstep',
            name='step',
        ),
        migrations.RemoveField(
            model_name='userstep',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timetracker',
            name='duration',
        ),
        migrations.AlterField(
            model_name='timetracker',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserStep',
        ),
        migrations.AddField(
            model_name='note',
            name='time_tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='thrivetracker.timetracker'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
