# Generated by Django 4.2 on 2023-04-12 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thrivetracker', '0016_note_remove_userprofile_money_tracker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_per_day', models.DecimalField(decimal_places=2, max_digits=100)),
                ('time_per_day', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='timetracker',
            name='money_tracker',
        ),
        migrations.AddField(
            model_name='token',
            name='time_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='thrivetracker.timetracker'),
        ),
        migrations.AlterField(
            model_name='note',
            name='time_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='thrivetracker.timetracker'),
        ),
        migrations.AlterField(
            model_name='timetracker',
            name='user_addiction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thrivetracker.useraddiction'),
        ),
        migrations.DeleteModel(
            name='MoneyTracker',
        ),
        migrations.AddField(
            model_name='saving',
            name='time_tracker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thrivetracker.timetracker'),
        ),
        migrations.AddField(
            model_name='saving',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetracker',
            name='savings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thrivetracker.saving'),
        ),
    ]
