# Generated by Django 4.2 on 2023-04-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0017_saving_remove_timetracker_money_tracker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='mood',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='triggers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
