# Generated by Django 4.2 on 2023-04-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0019_saving_money_per_day_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='time_per_day',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='time_tracker',
        ),
    ]
