# Generated by Django 4.2 on 2023-04-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0020_remove_saving_time_per_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='time_tracker',
            new_name='time_tracker_id',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='saving',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='timetracker',
            old_name='savings',
            new_name='savings_id',
        ),
        migrations.RenameField(
            model_name='timetracker',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='time_tracker',
            new_name='time_tracker_id',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='useraddiction',
            old_name='user',
            new_name='user_id',
        ),
    ]
