# Generated by Django 4.2 on 2023-04-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0021_rename_time_tracker_note_time_tracker_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='time_tracker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='thrivetracker.timetracker'),
        ),
    ]
