# Generated by Django 4.2 on 2023-04-13 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thrivetracker', '0022_saving_time_tracker_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='time_tracker_id',
            new_name='time_tracker',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='timetracker',
            old_name='savings_id',
            new_name='savings',
        ),
        migrations.RenameField(
            model_name='timetracker',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='time_tracker_id',
            new_name='time_tracker',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='useraddiction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='time_tracker_id',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='user_id',
        ),
        migrations.AddField(
            model_name='saving',
            name='time_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings_time_tracker', to='thrivetracker.timetracker'),
        ),
        migrations.AddField(
            model_name='saving',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
