# Generated by Django 4.2 on 2023-04-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0025_remove_timetracker_savings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetracker',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
