# Generated by Django 4.2 on 2023-04-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrivetracker', '0026_alter_timetracker_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddiction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Saving',
        ),
        migrations.DeleteModel(
            name='UserAddiction',
        ),
    ]
