# Generated by Django 4.2.5 on 2023-09-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThriveTrackerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('username', models.CharField(max_length=200, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=300, verbose_name='Venue Address')),
                ('zip_code', models.CharField(max_length=15, verbose_name='Venue Zip Code')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Venue Phone')),
                ('web', models.URLField(verbose_name='Venue Website')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Venue Email')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('manager', models.CharField(max_length=200, verbose_name='Event Manager')),
                ('description', models.TextField(blank=True, verbose_name='Event Description')),
                ('attendees', models.ManyToManyField(blank=True, to='addiction_calendar.thrivetrackeruser')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addiction_calendar.venue')),
            ],
        ),
    ]
