# Generated by Django 4.2.5 on 2023-09-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addiction_calendar', '0003_alter_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Venue Owner'),
        ),
    ]
