# Generated by Django 4.2.5 on 2023-09-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetracker',
            old_name='timetracker_user',
            new_name='thrivetracker_user',
        ),
    ]
